const ProductDetails = {
  //phones
  phones: [
    {
      id: 1,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-1-img-1_2.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-1-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-1-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-1-img-4.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-1-img-5.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-1-img-6.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-1-img-7.jpg",
      ],
      title: "گوشی موبایل هوآوی مدل Y8p دو سیم کارت ظرفیت 128 گیگابایت",
      engName: "Huawei Y8p Dual SIM 128GB Mobile Phone",
      Brand: "Huawei",
      category: "phone",
      colors: ["blue", "red"],
      mainProps: {
        chip: "Kirin 710F (12 nm)",
        freq: "1.7 - 2.2 گیگاهرتز",
        storage: "128 گیگابایت",
      },
      warranty: "18",
      price: 4750000,
      discount: [true, 15],
    },
    {
      id: 2,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-2-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-2-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-2-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-2-img-4.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-2-img-5.jpg",
      ],
      title: "گوشی موبایل شیائومی مدل POCO X3 دو سیم‌ کارت ظرفیت 128 گیگابایت",
      engName: "Xiaomi POCO X3 Dual SIM 128GB Mobile Phone",
      Brand: "Xiaomi",
      category: "phone",
      colors: ["black"],
      mainProps: {
        chip: "Qualcomm SM7150-AC Snapdragon 732G (8 nm)",
        freq: "1.8-2.3 گیگاهرتز",
        storage: "128 گیگابایت",
      },
      warranty: "18",
      price: 6450000,
      discount: [true, 10],
    },
    {
      id: 3,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-3-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-3-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-3-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-3-img-4.jpg",
      ],
      title:
        "گوشی موبایل شیائومی مدل Poco X3 Pro دو سیم‌ کارت ظرفیت 256 گیگابایت",
      engName: "Xiaomi Poco X3 Pro Dual SIM 256GB Mobile Phone",
      Brand: "Xiaomi",
      category: "phone",
      colors: ["blue", "bronze"],
      mainProps: {
        chip: "Qualcomm Snapdragon 860 (7 nm)",
        freq: "1.78-2.42 گیگاهرتز",
        storage: "256 گیگابایت",
      },
      warranty: "18",
      price: 7050000,
      discount: [false, 0],
    },
    {
      id: 4,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-4-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-4-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-4-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-4-img-4.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-4-img-5.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/mobile-4-img-6.jpg",
      ],
      title:
        "گوشی موبایل سامسونگ مدل Galaxy A10s SM-A107F دو سیم کارت ظرفیت 32 گیگابایت",
      engName: "Samsung Galaxy A10s SM-A107F Dual SIM 32GB Mobile Phone",
      Brand: "Samsung",
      category: "phone",
      colors: ["blue", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "2.0 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 3250000,
      discount: [true, 25],
    },
  ],
  tablets: [
    {
      id: 1,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-1-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-1-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-1-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-1-img-4.jpg",
      ],
      title: "تبلت هوآوی مدل MediaPad M5 Lite 8",
      engName: "Huawei MediaPad M5 Lite 8 32/3GB RAM",
      Brand: "Huawei",
      category: "tablet",
      colors: ["gray", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "2.0 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 5790000,
      discount: [true, 20],
    },
    {
      id: 2,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-2-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-2-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-2-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-2-img-4.jpg",
      ],
      title: "تبلت هوآوی مدل Huawei MatePad T10 LTE",
      engName: "Samsung MatePad T10 LTE 16GB Tablet",
      Brand: "Huawei",
      category: "tablet",
      colors: ["blue", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "3.1 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 3100000,
      discount: [false, 0],
    },
    {
      id: 3,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-3-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-3-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-3-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-3-img-4.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-3-img-5.jpg",
      ],
      title: "تبلت هوآوی مدل Huawei MatePad T10 LTE",
      engName: "LG MatePad T10 LTE 16GB Tablet",
      Brand: "Huawei",
      category: "tablet",
      colors: ["blue", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "3.1 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 3100000,
      discount: [false, 0],
    },
    {
      id: 4,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-4-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-4-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/tablet-4-img-3.jpg",
      ],
      title: "تبلت هوآوی مدل Huawei MatePad T12 LTE",
      engName: "Apple MatePad T10 LTE 16GB Tablet",
      Brand: "Huawei",
      category: "tablet",
      colors: ["blue", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "3.1 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 3100000,
      discount: [true, 25],
    },
  ],
  laptops: [
    {
      id: 1,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-1-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-1-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-1-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-1-img-4.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-1-img-5.jpg",
      ],
      title: "لپتاپ هوآوی مدل MediaPad M5 Lite 8",
      engName: "Huawei Laptop M5 Lite 8 32/3GB RAM",
      Brand: "Huawei",
      category: "laptop",
      colors: ["gray", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "2.0 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 11790000,
      discount: [true, 35],
    },
    {
      id: 2,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-2-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-2-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-2-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-2-img-4.jpg",
      ],
      title: "لپتاپ سامسونگ مدل MediaPad M5 Lite 8",
      engName: "Samsung Laptop M5 Lite 8 32/3GB RAM",
      Brand: "Huawei",
      category: "laptop",
      colors: ["gray", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "2.0 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 13790000,
      discount: [true, 25],
    },
    {
      id: 3,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-3-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-3-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-3-img-3.jpg",
      ],
      title: "لپتاپ ال جی مدل MediaPad M5 Lite 8",
      engName: "LG Laptop M5 Lite 8 32/3GB RAM",
      Brand: "Huawei",
      category: "laptop",
      colors: ["gray", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "2.0 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 15790000,
      discount: [false, 0],
    },
    {
      id: 4,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-4-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-4-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/laptop-4-img-3.jpg",
      ],
      title: "لپتاپ اپل مدل MediaPad M5 Lite 8",
      engName: "Apple Laptop M5 Lite 8 32/3GB RAM",
      Brand: "Huawei",
      category: "laptop",
      colors: ["gray", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "2.0 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 15790000,
      discount: [false, 0],
    },
  ],
  watches: [
    {
      id: 1,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-1-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-1-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-1-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-1-img-4.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-1-img-5.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-1-img-6.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-1-img-7.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-1-img-8.jpg",
      ],
      title: "ساعت سامسونگ مدل MediaPad M5 Lite 8",
      engName: "SamSung Smart Watch M5 Lite 8 32/3GB RAM",
      Brand: "Huawei",
      category: "watche",
      colors: ["gray", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "2.0 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 1579000,
      discount: [true, 12],
    },
    {
      id: 2,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-2-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-2-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-2-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-2-img-4.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-2-img-5.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-2-img-6.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-2-img-7.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-2-img-8.jpg",
      ],
      title: "ساعت هوآوی مدل MediaPad M5 Lite 8",
      engName: "Huawei Smart Watch M5 Lite 8 32/3GB RAM",
      Brand: "Huawei",
      category: "watche",
      colors: ["gray", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "2.0 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 1379000,
      discount: [true, 16],
    },
    {
      id: 3,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-3-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-3-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-3-img-3.jpg",
      ],
      title: "ساعت ال جی مدل MediaPad M5 Lite 8",
      engName: "LG Smart Watch M5 Lite 8 32/3GB RAM",
      Brand: "Huawei",
      category: "watche",
      colors: ["gray", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "2.0 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 1479000,
      discount: [false, 0],
    },
    {
      id: 4,
      imgs: [
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-4-img-1.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-4-img-2.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-4-img-3.jpg",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-4-img-4.png",
        "https://shop-api.s3.ir-thr-at1.arvanstorage.com/watch-4-img-5.jpg",
      ],
      title: "ساعت شیائومی مدل MediaPad M5 Lite 8",
      engName: "Xiaomi Smart Watch M5 Lite 8 32/3GB RAM",
      Brand: "Huawei",
      category: "watche",
      colors: ["gray", "black"],
      mainProps: {
        chip: "Mediatek MT6762 Helio P22 (12 nm) Chipset",
        freq: "2.0 گیگاهرتز",
        storage: "32 گیابایت",
      },
      warranty: "18",
      price: 1679000,
      discount: [false, 0],
    },
  ],
};

export default ProductDetails;
